Create a Pandas Series from the list [10, 20, 30, 40, 50]. Print the Series, its index, and data type. Then create a DataFrame with columns "Name", "Age", and "City" containing at least 4 rows of data.

In [1]:
import pandas as pd

list_a = [10,20,30,40,50]

pd_series = pd.Series(list_a)

print(pd_series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

creating a dataframe with columns "Name", "Age", and "City" containing at least 4 rows of data.

In [4]:
df = pd.DataFrame([
    {
        'Name': 'Thanos',
        'Age' : '1000',
        'City' : 'Vormir'
    },
    {
        'Name': 'Thor',
        'Age' : '1500',
        'City' : 'Asgard'
    },
    {
        'Name': 'Goblin',
        'Age' : '50',
        'City' : 'NY'
    },
    {
        'Name': 'Loki',
        'Age' : '500',
        'City' : 'Asgard'
    }
])

df

     Name   Age    City
0  Thanos  1000  Vormir
1    Thor  1500  Asgard
2  Goblin    50      NY
3    Loki   500  Asgard

Using any DataFrame, write code to print the number of rows and columns, column data types (.dtypes), and summary statistics (.describe()).

In [7]:
st_df = pd.read_csv('student_data.csv')

st_df.describe()
st_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     str
 1   FullName              20 non-null     str
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     str
 6   EnrollmentDate        20 non-null     str
 7   Instructor            20 non-null     str
 8   Location              20 non-null     str
dtypes: float64(3), str(6)
memory usage: 2.6 KB

Create a DataFrame using the dictionary below:</br>
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],</br>
        'Price': [10, 50, 5, 7],</br>
        'Quantity': [100, 60, 200, 150]</br>
}

In [20]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

a_df = pd.DataFrame(data)
print(a_df)
print("_________________________")
print(a_df.columns)
print("_________________________")
print(a_df.index)
print("_________________________")

print(a_df['Product'])
print("_________________________")
print(a_df.loc[0])

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150
_________________________
Index(['Product', 'Price', 'Quantity'], dtype='str')
_________________________
RangeIndex(start=0, stop=4, step=1)
_________________________
0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: str
_________________________
Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object

Using .loc[] and .iloc[], show the first row, the second column, and a 2×2 block    from the middle of your DataFrame.

In [30]:
# st_df.head()
first_row = st_df.loc[0]
# print(first_row)
print("_________________________")
# print(st_df['FullName'])
# print(st_df.loc[1,'FullName'])

print(st_df.loc[6:7,['FullName','Data Structure Marks']])

_________________________
         FullName  Data Structure Marks
6  Mahmudul Hasan                  80.0
7     Nadia Islam                  81.0

Create a 4×3 DataFrame of student names and marks. Drop one column using .drop(), drop one row by index

In [35]:
n_df = pd.DataFrame([
    {
       'Name' : 'Jhon Doe',
       'Marks' : 85
    },
    {
       'Name' : 'Gill Cris',
       'Marks' : 90
    },
    {
       'Name' : 'Tailor Gomez',
       'Marks' : 95
    },
    {
       'Name' : 'Adelin Monroe',
       'Marks' : 98
    },
])

# n_df

# drop one colums
# no_marks = n_df.drop('Marks',axis=1)
# no_marks

# drop one row
no_zero = n_df.drop(0)
no_zero

            Name  Marks
1      Gill Cris     90
2   Tailor Gomez     95
3  Adelin Monroe     98

Create a DataFrame of employees with columns "Name", "Department", and "Salary". Sort it by "Salary" in ascending order and by "Name" in descending order.

In [41]:
emp_df = pd.DataFrame([
    {
        'Name' : 'Clint Barton',
        'Department': 'IT',
        'Salary' : 980000
    },
    {
        'Name' : 'Steve Rojers',
        'Department': 'Management',
        'Salary' : 850000
    },
    {
        'Name' : 'Tony Stark',
        'Department': 'Marketing',
        'Salary' : 750000
    },
    {
        'Name' : 'Thor Odinson',
        'Department': 'Finance',
        'Salary' : 740000
    },
])

sorted_emp_df = emp_df.sort_values(['Salary','Name'],ascending=[1,0])

sorted_emp_df

           Name  Department  Salary
3  Thor Odinson     Finance  740000
2    Tony Stark   Marketing  750000
1  Steve Rojers  Management  850000
0  Clint Barton          IT  980000

Create a DataFrame of 8 students with columns "Name" and "Score". Filter and print students with Score > 60 and those with Score < 40.

In [ ]:
student_df = pd.DataFrame([
  {
    "Name": "Alice Johnson",
    "Score": 92
  },
  {
    "Name": "Mark Thompson",
    "Score": 78
  },
  {
    "Name": "Saira Khan",
    "Score": 85
  },
  {
    "Name": "Leo Garcia",
    "Score": 91
  },
  {
    "Name": "Chris Timber",
    "Score": 39
  },
  {
    "Name": "James Wilson",
    "Score": 88
  },
  {
    "Name": "Amara Okafor",
    "Score": 45
  },
  {
    "Name": "David Miller",
    "Score": 82
  }
]
)


# student_df

score_g60 = student_df.loc[(student_df['Score'] > 60)]

# score_g60

score_l40 = student_df.loc[student_df['Score'] < 40]
score_l40