In [10]:
import pandas as pd

df = pd.read_csv("Practice.csv")
df

   EmployeeID EmployeeName   Age   Salary  Price  Marks1  Marks2  Marks3
0        E101        Alice  25.0  50000.0   1200      85      90      88
1        E102          Bob  30.0  60000.0   1500      78      82      80
2        E103      Charlie  22.0  52000.0   1100      92      95      90
3        E101        Alice  25.0  50000.0   1200      85      90      88
4        E104        David  45.0  80000.0   2500      88      85      89
5        E105          Eve  29.0  58000.0   1300      76      79      81
6        E106        Frank   NaN  75000.0   2200      90      91      92
7        E107        Grace  34.0      NaN   1900      81      83      80
8        E108        Heidi  38.0      NaN   1800      84      86      88
9        E109         Ivan  26.0  53000.0   1400      95      92      94
10       E102          Bob  30.0  60000.0   1500      78      82      80

In [4]:
df['Discounted_Price'] = df['Price'] - (df['Price'] * 0.1)
df.to_csv("discounted_products.csv")

Check duplicate and clean

In [35]:
df.duplicated(subset='EmployeeID').sum()
cleaned_df = df.drop_duplicates(subset='EmployeeID')
cleaned_df

  EmployeeID EmployeeName   Age   Salary  Price  Marks1  Marks2  Marks3
0       E101        Alice  25.0  50000.0   1200      85      90      88
1       E102          Bob  30.0  60000.0   1500      78      82      80
2       E103      Charlie  22.0  52000.0   1100      92      95      90
4       E104        David  45.0  80000.0   2500      88      85      89
5       E105          Eve  29.0  58000.0   1300      76      79      81
6       E106        Frank  30.4  75000.0   2200      90      91      92
7       E107        Grace  34.0      NaN   1900      81      83      80
8       E108        Heidi  38.0      NaN   1800      84      86      88
9       E109         Ivan  26.0  53000.0   1400      95      92      94

Handling missing values

In [36]:
count_missing_age = df['Age'].isnull().sum()
count_missing_salary = df['Salary'].isnull().sum()

print(count_missing_age,count_missing_salary)

cleaned_df['Age'] = cleaned_df['Age'].fillna(cleaned_df['Age'].mean(),inplace=True)
cleaned_df

0 2

C:\Users\mehra\AppData\Local\Temp\ipykernel_16788\867218482.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  cleaned_df['Age'] = cleaned_df['Age'].fillna(cleaned_df['Age'].mean(),inplace=True)

  EmployeeID EmployeeName   Age   Salary  Price  Marks1  Marks2  Marks3
0       E101        Alice  25.0  50000.0   1200      85      90      88
1       E102          Bob  30.0  60000.0   1500      78      82      80
2       E103      Charlie  22.0  52000.0   1100      92      95      90
4       E104        David  45.0  80000.0   2500      88      85      89
5       E105          Eve  29.0  58000.0   1300      76      79      81
6       E106        Frank  30.4  75000.0   2200      90      91      92
7       E107        Grace  34.0      NaN   1900      81      83      80
8       E108        Heidi  38.0      NaN   1800      84      86      88
9       E109         Ivan  26.0  53000.0   1400      95      92      94

In [48]:
cleaned_df.dropna(subset=['Salary'],inplace=True)

Statistical Functions

In [38]:
marks1_min = cleaned_df['Marks1'].min()
marks2_min = cleaned_df['Marks2'].min()
marks3_min = cleaned_df['Marks3'].min()

print(f"Min of\nMarks1: {marks1_min}\nMarks2: {marks2_min}\nMarks3: {marks3_min}")

marks1_mean = cleaned_df['Marks1'].mean()
marks2_mean = cleaned_df['Marks2'].mean()
marks3_mean = cleaned_df['Marks3'].mean()

print(f"\nMean of\nMarks1: {marks1_mean}\nMarks2: {marks2_mean}\nMarks3: {marks3_mean}")

Min of
Marks1: 76
Marks2: 79
Marks3: 80

Mean of
Marks1: 85.44444444444444
Marks2: 87.0
Marks3: 86.88888888888889

In [49]:
cleaned_df['Total Marks'] = cleaned_df.iloc[:,5:8].sum(axis=1)
cleaned_df

,EmployeeID,EmployeeName,Age,Salary,Price,Marks1,Marks2,Marks3,Total Marks
0,E101,Alice,25.0,50000.0,1200,85,90,88,263
1,E102,Bob,30.0,60000.0,1500,78,82,80,240
2,E103,Charlie,22.0,52000.0,1100,92,95,90,277
4,E104,David,45.0,80000.0,2500,88,85,89,262
5,E105,Eve,29.0,58000.0,1300,76,79,81,236
6,E106,Frank,30.4,75000.0,2200,90,91,92,273
9,E109,Ivan,26.0,53000.0,1400,95,92,94,281

In [51]:
cleaned_df['Total Marks'].std()

cleaned_df.to_csv('cleaned_data.csv')