### From 2D array

In [3]:
import pandas as pd

list_2d = [['Jhon Doe',25],['Chris Evans',40],['Robert Jr.',[50]]]

list_2d_df = pd.DataFrame(list_2d)

print(list_2d_df)

             0     1
0     Jhon Doe    25
1  Chris Evans    40
2   Robert Jr.  [50]

With custom column name

In [ ]:
import pandas as pd

list_2d = [['Jhon Doe',25],['Chris Evans',40],['Robert Jr.',[50]]] 

# pd.DataFrame(list_2d,columns=['Name','Age'])
print((pd.DataFrame(list_2d,columns=['Name','Age'])))

          Name   Age
0     Jhon Doe    25
1  Chris Evans    40
2   Robert Jr.  [50]

With Custom index/row name

In [6]:
import pandas as pd

list_2d = [['Jhon Doe',25],['Chris Evans',40],['Robert Jr.',[50]]] 

# pd.DataFrame(list_2d,columns=['Name','Age'])
print((pd.DataFrame(list_2d,columns=['Name','Age'], index=[1,2,3])))

          Name   Age
1     Jhon Doe    25
2  Chris Evans    40
3   Robert Jr.  [50]

### From tuple to df

In [7]:
tuple_st = (('Jhon Doe',20),('Alice Kim',65))

print(pd.DataFrame(tuple_st, columns=['Name','Age']))

        Name  Age
0   Jhon Doe   20
1  Alice Kim   65

### From dictionary to df

In [ ]:
dict_st = {
    'Name' : ['Thor Odinson','Thanos','Loki'],
    'Age' : [1500,2000,1000]
}
# number of items in each key must be equal

# pd.DataFrame(dict_st)
# pd.DataFrame(dict_st, index=[1,2,3])

           Name   Age
1  Thor Odinson  1500
2        Thanos  2000
3          Loki  1000

### From list of dictionary to df

In [13]:
st_data = [
    {'Name' : 'Jhon Doe','Age': 25,'City': 'Toronto'},
    {'Name' : 'Harvey Dent','Age': 34,'City': 'Ajax'},
    {'Name' : 'Jeremy Renner','Age': 40,'City': 'Calgary'}
]

# print(st_data)

pd.DataFrame(st_data)

            Name  Age     City
0       Jhon Doe   25  Toronto
1    Harvey Dent   34     Ajax
2  Jeremy Renner   40  Calgary