In [2]:
import pandas as pd

df = pd.DataFrame(
    {
        "Name" : ["Akkas","Jakkas","Rakkas"],
        "Age" : [12,14,11],
        "Marks": [65,85,43]
    }
)

df

     Name  Age  Marks
0   Akkas   12     65
1  Jakkas   14     85
2  Rakkas   11     43

Assign grade based on marks

In [ ]:
def assign_grade(marks):
    if marks >= 80:
        return 'A'
    elif marks >= 60:
        return 'B'
    else:
        return 'C'
    

df["Grade"] = df["Marks"].apply(assign_grade)

df

# save this dataframe as csv file
df.to_csv("student_grade.csv")

Sort based on marks

In [ ]:
# sorted_marks = df.sort_values('Marks',ascending=True) # or
sorted_marks = df.sort_values(by = 'Marks',ascending=False) 
sorted_marks

     Name  Age  Marks Grade
1  Jakkas   14     85     A
0   Akkas   12     65     B
2  Rakkas   11     43     C