In [1]:
import pandas as pd

data = {
    "Name": [
        "Jhon Doe", "David Ross", "Sarah Chen", "Mike Ross", "Emily White",
        "Liam O'Connor", "Sofia Rodriguez", "Aisha Khan", "Yuki Tanaka",
        "Kwame Mensah", "Elena Petrova", "Jack Harrison"
    ],
    "City": [
        "North York", "New York", "Toronto", "Toronto", "London",
        "Dublin", "Madrid", "Dubai", "Tokyo",
        "Accra", "Berlin", "Sydney"
    ],
    "Country": [
        "Canada", "US", "Canada", "Canada", "UK",
        "Ireland", "Spain", "UAE", "Japan",
        "Ghana", "Germany", "Australia"
    ],
    "Job Title": [
        "Software Engineer", "Backend Developer", "Data Scientist", "Project Manager", "UX Designer",
        "DevOps Engineer", "Frontend Developer", "Product Manager", "Systems Architect",
        "Data Analyst", "Security Engineer", "QA Engineer"
    ],
    "Salary": [
        160000, 155000, 145000, 130000, 120000,
        140000, 115000, 170000, 180000,
        95000, 135000, 110000
    ]
}

df = pd.DataFrame(data)

df

               Name        City    Country           Job Title  Salary
0          Jhon Doe  North York     Canada   Software Engineer  160000
1        David Ross    New York         US   Backend Developer  155000
2        Sarah Chen     Toronto     Canada      Data Scientist  145000
3         Mike Ross     Toronto     Canada     Project Manager  130000
4       Emily White      London         UK         UX Designer  120000
5     Liam O'Connor      Dublin    Ireland     DevOps Engineer  140000
6   Sofia Rodriguez      Madrid      Spain  Frontend Developer  115000
7        Aisha Khan       Dubai        UAE     Product Manager  170000
8       Yuki Tanaka       Tokyo      Japan   Systems Architect  180000
9      Kwame Mensah       Accra      Ghana        Data Analyst   95000
10    Elena Petrova      Berlin    Germany   Security Engineer  135000
11    Jack Harrison      Sydney  Australia         QA Engineer  110000

simple string filtering

In [2]:
df.loc[df['City'].str.contains('York',case='False')]

         Name        City Country          Job Title  Salary
0    Jhon Doe  North York  Canada  Software Engineer  160000
1  David Ross    New York      US  Backend Developer  155000

### string filtering with regex

all cities starting with T

In [7]:
df.loc[df['City'].str.contains(r'T')]

          Name     City Country          Job Title  Salary
2   Sarah Chen  Toronto  Canada     Data Scientist  145000
3    Mike Ross  Toronto  Canada    Project Manager  130000
8  Yuki Tanaka    Tokyo   Japan  Systems Architect  180000

all cities ending with 'n'

In [8]:
df.loc[df['City'].str.contains(r'n$')]

             Name    City  Country          Job Title  Salary
4     Emily White  London       UK        UX Designer  120000
5   Liam O'Connor  Dublin  Ireland    DevOps Engineer  140000
10  Elena Petrova  Berlin  Germany  Security Engineer  135000

All Developers and Engineers

In [14]:
df.loc[df['Job Title'].str.contains(r'Developer|Engineer')] # be careful about white space, it counts white spaces as well

               Name        City    Country           Job Title  Salary
0          Jhon Doe  North York     Canada   Software Engineer  160000
1        David Ross    New York         US   Backend Developer  155000
5     Liam O'Connor      Dublin    Ireland     DevOps Engineer  140000
6   Sofia Rodriguez      Madrid      Spain  Frontend Developer  115000
10    Elena Petrova      Berlin    Germany   Security Engineer  135000
11    Jack Harrison      Sydney  Australia         QA Engineer  110000

All names that start with a vowel

In [23]:
df.loc[df['Name'].str.contains(r'^[AEIOU]')]

             Name    City  Country          Job Title  Salary
4     Emily White  London       UK        UX Designer  120000
7      Aisha Khan   Dubai      UAE    Product Manager  170000
10  Elena Petrova  Berlin  Germany  Security Engineer  135000