In [1]:
import pandas as pd

df = pd.read_csv('student_completed_data.csv')

df.sample(5)

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
0,PH0001,Sahil Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266

In [3]:
instructor_group = df.groupby('Instructor')
instructor_group

In [4]:
for instructor, df_instruct in instructor_group:
    print(instructor)
    display(df_instruct)

Mr. David

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278

Mr. Karim

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

Ms. Salma

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Sahil Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234

In [5]:
instructor_group.max()

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Location,Total Marks
Instructor,,,,,,,
Mr. David,PH0018,Wahiduzzaman,Completed,2024-09-07,2024-12-31,Sylhet,291
Mr. Karim,PH0020,Tariq Hasan,Completed,2024-08-11,2024-11-07,Sylhet,291
Ms. Salma,PH0016,Ziaur Rahman,Completed,2024-09-01,2024-12-23,Rajshahi,300

In [6]:
instructor_group.min()

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Location,Total Marks
Instructor,,,,,,,
Mr. David,PH0005,Afsana Mimi,Completed,2024-01-04,2024-03-16,Chattogram,236
Mr. Karim,PH0002,Faria Rahman,Completed,2024-02-12,2024-06-08,Dhaka,253
Ms. Salma,PH0001,Imran Hossain,Completed,2024-03-22,2024-05-01,Dhaka,234

In [7]:
instructor_group.describe()

           Total Marks                                                      \
                 count        mean        std    min    25%    50%     75%
Instructor
Mr. David          9.0  266.555556  20.063095  236.0  249.0  272.0  285.00
Mr. Karim          7.0  273.000000  12.261049  253.0  268.0  271.0  280.00
Ms. Salma          4.0  262.250000  29.055980  234.0  243.0  257.5  276.75


              max
Instructor
Mr. David   291.0
Mr. Karim   291.0
Ms. Salma   300.0

In [8]:
mean_marks = instructor_group['Total Marks'].mean()
mean_marks

Instructor
Mr. David    266.555556
Mr. Karim    273.000000
Ms. Salma    262.250000
Name: Total Marks, dtype: float64

In [9]:
# replacing NaN values of Total Marks by group wise average mark
df['Total Marks'] = df['Total Marks'].fillna(df['Instructor'].map(mean_marks))

df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Sahil Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253