In [ ]:
import pandas as pd

df = pd.read_csv('../student_data.csv')

df

Change/Assigne values of specific cell

In [ ]:
df.loc[1,'Python Marks'] = 90
df.loc[1,'CompletionStatus'] = 'Completed'

df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,90.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram

Update a cell value

In [ ]:
df.loc[1:3,'Python Marks'] += 2

df.head(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,94.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,89.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,86.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram