In [3]:
import pandas as pd

df = pd.read_csv('../student_data.csv')
df.sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet

unique() counts 'Nan'

In [3]:
df['Python Marks'].unique()

array([88., nan, 85., 82., 95., 78., 76., 91., 87., 79., 84., 93., 89.])

In [ ]:
len(df['Python Marks'].unique())

13

nunique() does not count 'Nan'

In [ ]:
df['Python Marks'].nunique()

12

nunique() can work on entire dataframe

In [6]:
df.nunique()

StudentID               20
FullName                20
Data Structure Marks    12
Algorithm Marks         12
Python Marks            12
CompletionStatus         3
EnrollmentDate          20
Instructor               3
Location                 5
dtype: int64

In [ ]:
df.isnull() # True if null, False otherwise

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,True,True,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,True,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,True,True,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,True,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,True,True,True,False,False,False,False
19,False,False,False,False,False,False,False,False,False

In [ ]:
df['Python Marks'].isnull() # True -> if null, False otherwise

0     False
1      True
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15     True
16    False
17    False
18     True
19    False
Name: Python Marks, dtype: bool

notnull()...opposite of isnull()</br>
If null,--> False, otherwise True

In [9]:
df['Python Marks'].notnull()

0      True
1     False
2      True
3      True
4      True
5      True
6     False
7      True
8      True
9      True
10     True
11     True
12     True
13    False
14     True
15    False
16     True
17     True
18    False
19     True
Name: Python Marks, dtype: bool

In [ ]:
df['Python Marks'].hasnans # Output: True, because Nan exists

True

In [ ]:
df['StudentID'].hasnans # not null values here

False